apiVersion: watsonxdata.ibm.com/v1
kind: WxdAddon
metadata:
  name: wxdaddon
spec:
  license:
    accept: true
    license: Enterprise
  fileStorageClass: PATCHED_BY_KUSTOMIZE
  blockStorageClass: PATCHED_BY_KUSTOMIZE
  version: 1.0.1
