apiVersion: operator.ibm.com/v1
kind: NamespaceScope
metadata:
  name: common-service
spec:
  csvInjector:
    enable: true
  namespaceMembers:
    - cp4d-operators
    - cp4d
  restartLabels:
    intent: projected
  license:
    accept: true
  