kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nss-managed-role-from-cp4d-operators
  namespace: cp4d
subjects:
- kind: ServiceAccount
  name: ibm-namespace-scope-operator
  namespace: cp4d-operators
roleRef:
  kind: Role
  name: nss-managed-role-from-cp4d-operators
  apiGroup: rbac.authorization.k8s.io