apiVersion: cpd.ibm.com/v1
kind: Ibmcpd
metadata:
  name: ibmcpd-cr                                                       
spec:
  storageClass: ibmc-file-gold-gid
  zenCoreMetadbStorageClass: ibmc-block-gold
  
