kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argo-role
rules:
  - verbs:
      - '*'
    apiGroups:
      - ""
    resources:
      - serviceaccounts
  - verbs:
      - '*'
    apiGroups:
      - batch
    resources:
      - jobs
  - verbs:
      - '*'
    apiGroups:
      - cpd.ibm.com
    resources:
      - ibmcpds
  - verbs:
      - '*'
    apiGroups:
      - watsonxdata.ibm.com
    resources:
      - wxdaddons
  - verbs:
      - '*'
    apiGroups:
      - operator.ibm.com
    resources:
      - commonservices
