apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: openshift-operators
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./components/shared/cert-manager/base
    targetRevision: 'HEAD'
    repoURL: https://github.com/thomas-mattsson/cp4d-watsonx-gitops.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
