apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: watsonx-data-addon
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "100"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cp4d
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./envs/odf/watsonx
    targetRevision: 'HEAD'
    repoURL: https://github.com/thomas-mattsson/cp4d-watsonx-gitops.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true