apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: watsonx-data-operator
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "25"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/thomas-mattsson/cp4d-watsonx-gitops.git
    targetRevision: 'HEAD'
    path: 'components/cp4d/watsonx/operator/base'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 'openshift-operators'
  syncPolicy:
    automated:
      selfHeal: true
