apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-licensing-operator-app
  namespace: ibm-licensing
spec:
  channel: v4.0
  installPlanApproval: Automatic
  name: ibm-licensing-operator-app
  source: ibm-operator-catalog #ibm-licensing-catalog
  sourceNamespace: openshift-marketplace